version: '3.8'

services:
  irccs-centro-ricerca:
    container_name: irccs-centro-ricerca
    image: nexus.infocube.it/org.quarkus.irccs.microservice/irccs-centroricerca:1.0.0-SNAPSHOT
    restart: always
    ports:
      - 8080
    networks:
      - irccs-docker_default
    volumes:
      - ./config:/deployments/config
networks:
  irccs-docker_default:
    external: true

