version: '3.7'

services:
  fhir:
    container_name: fhir
    image: "irccs/fhir-server:1.0.2"
    environment:
      hapi.fhir.allow_external_references: "true"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db

  db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    ports:
      - "5432:5432"

  mysql:
    image: "mysql:5.6"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: irccs
      MYSQL_PASSWORD: irccs

  cache:
    image: redis:7.0-rc
    ports:
      - 6379:6379
    command: >
      --requirepass password


configs:
  hapi:
    file: ./hapi.application.yaml