networks:
  irccs:
    driver: bridge

services:
  irccs-microservice-clinical-reasoning:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-clinical-reasoning:${IRCCS_CLINICAL_REASONING_VERSION}
    container_name: irccs-clinical-reasoning
    volumes:
      - ./microservice-config:/deployments/config
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-auth:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-auth:${IRCCS_AUTH_VERSION}
    container_name: irccs-auth
    volumes:
      - ./microservice-config:/deployments/config
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-notification:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-notification:${IRCCS_NOTIFICATION_VERSION}
    container_name: irccs-notification
    volumes:
      - ./microservice-config-notification/application.properties:/deployments/config/application.properties
    env_file:
      - .env
    ports:
      - "8987:8080"
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-practitioner:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-practitioner:${IRCCS_PRACTITIONER_VERSION}
    container_name: irccs-practitioner
    volumes:
      - ./microservice-config:/deployments/config
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-centro-ricerca:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-centro-ricerca:${IRCCS_CENTRO_RICERCA_VERSION}
    container_name: irccs-centro-ricerca
    volumes:
      - ./microservice-config:/deployments/config
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-studio-clinico:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-studio-clinico:${IRCCS_STUDIO_CLINICO_VERSION}
    container_name: irccs-studio-clinico
    volumes:
      - ./microservice-config:/deployments/config
      - ./translations:/deployments/translations
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-anagrafica-pazienti:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-anagrafica-pazienti:${IRCCS_ANAGRAFICA_VERSION}
    container_name: irccs-anagrafica-pazienti
    ports:
      - "8976:8080"
    volumes:
      - ./microservice-config:/deployments/config
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-httpd:
    image: nexus.infocube.it/i3/irccs/irccs-httpd-dashboard/develop:${IRCCS_HTTPD_VERSION}
    container_name: irccs-httpd-dashboard
    ports:
      - "443:443"
    volumes:
      - ./httpd-config/irccs.conf:/usr/local/apache2/conf/sites/irccs.conf
      - ./httpd-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd-config/config-prod.js:/usr/local/apache2/htdocs/config.js
      - ./httpd-config/manuale-cliente:/usr/local/apache2/htdocs/manuale-cliente #documentazione antora
      - /home/savioadmin/cert-pasc-2026.crt:/usr/local/apache2/conf/ssl/cert-pasc-2026.crt:ro
      - /home/savioadmin/cert-pasc-2026.key:/usr/local/apache2/conf/ssl/cert-pasc-2026.key:ro
    networks:
      - irccs
  postgres-keycloak:
    image: postgres:${POSTGRES_KEYCLOAK_VERSION}
    hostname: postgres
    container_name: postgres-keycloak
    restart: always
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
      - ./microservice-config-webpush/postgres-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_KEYCLOAK_DB}
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
    networks:
      - irccs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_KEYCLOAK_USER} -d ${POSTGRES_KEYCLOAK_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  irccs-keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_VERSION}
    container_name: irccs-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${POSTGRES_KEYCLOAK_DB}
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME: ${KC_HOSTNAME}
      #KC_HOSTNAME_STRICT: true
      #KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: forwarded
      KC_HTTP_RELATIVE_PATH: /backoffice
    env_file:
      - .env
    restart: always
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "/opt/keycloak/bin/kc.sh build --db postgres && /opt/keycloak/bin/kc.sh start --hostname ${KC_HOSTNAME} --http-relative-path /backoffice --hostname-backchannel-dynamic false --import-realm -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      ]
    ports:
      - "127.0.0.1:9445:8080"
    volumes:
      - ./keycloak-config/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak-config/realm-export:/opt/keycloak/data/import
      - ./keycloak-config/realm-export:/export
      - ./keycloak-config/providers/:/opt/keycloak/providers/
    depends_on:
      - postgres-keycloak
    networks:
      - irccs
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 10

  irccs-hapi-fhir:
    image: hapiproject/hapi:${HAPI_IMAGE_VERSION}
    container_name: irccs-hapi-fhir
    ports:
      - "8080:8080"
    depends_on:
      - postgres-hapi-fhir
    volumes:
      - ./hapi-fhir-config/application.yaml:/home/application.yaml
      - ./terminology:/terminology
      - ./hapi-fhir-config/lucenefiles:/lucenefiles
    environment:
      SPRING_CONFIG_LOCATION: '/home/application.yaml'
    env_file:
      - .env
    networks:
      - irccs

  postgres-hapi-fhir:
    image: postgres:${POSTGRES_HAPI_VERSION}
    hostname: postgres
    container_name: postgres-hapi-fhir
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data_hapi:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${HAPI_DB_NAME}
      POSTGRES_USER: ${HAPI_DB_USER}
      POSTGRES_PASSWORD: ${HAPI_DB_PASSWORD}
    networks:
      - irccs

  cache:
    container_name: irccs-redis
    hostname: redis
    image: redis:${REDIS_VERSION}
    networks:
      - irccs
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  irccs-microservice-tac:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-tac:${IRCCS_TAC_VERSION}
    container_name: irccs-tac
    volumes:
      - ./microservice-config-tac:/deployments/config
      - ./dicom:/data
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-zammad:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-zammad:${IRCCS_ZAMMAD_VERSION}
    container_name: irccs-zammad
    volumes:
      - ./microservice-config-zammad:/deployments/config
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

  irccs-microservice-webpush:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-webpush:${IRCCS_WEBPUSH_VERSION}
    container_name: irccs-webpush
    hostname: irccs-webpush
    volumes:
      - ./microservice-config-webpush:/deployments/config
      - ./translations:/deployments/translations
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
      postgres-keycloak:
        condition: service_healthy
    restart: always

  irccs-antora-docs:
    image: nexus.infocube.it/i3/irccs/antora-docs:${IRCCS_ANTORA_DOCS_VERSION}
    container_name: irccs-antora-docs
    restart: always
    networks:
      - irccs

  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
  #  container_name: irccs-elasticsearch
  #  environment:
  #    - discovery.type=single-node
  #    - cluster.name=snowstorm-cluster
  #    - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
  #  volumes:
  #    - elasticsearch_data:/usr/share/elasticsearch/data
  #  networks:
  #    - irccs
  #  healthcheck:
  #    test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -qE '\"status\":\"(green|yellow)\"'"]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 10
  #  restart: always

  #snowstorm:
  #  image: snomedinternational/snowstorm:latest
  #  container_name: irccs-snowstorm
  #  command: --elasticsearch.urls=http://elasticsearch:9200
  #  environment:
  #    - JDK_JAVA_OPTIONS=--add-opens java.base/java.util=ALL-UNNAMED
  #  depends_on:
  #    elasticsearch:
  #      condition: service_healthy
  #  ports:
  #    - "8085:8080"
  #  networks:
  #    - irccs
  #  restart: always

  irccs-microservice-patient-interview:
    image: nexus.infocube.it/org.quarkus/irccs-microservice-patient-interview:${IRCCS_PATIENT_INTERVIEW_VERSION}
    container_name: irccs-patient-interview
    volumes:
      - ./microservice-config:/deployments/config
    env_file:
      - .env
    networks:
      - irccs
    depends_on:
      irccs-keycloak:
        condition: service_healthy
    restart: always

volumes:
  postgres_data_hapi:
  postgres_data_keycloak:
  redis_data:
  elasticsearch_data:
