version: '3.7'

services:
  java-env:
    image: "irccs/19-jdk-slim"
    volumes:
      - ./services/:/home

  fhir:
    container_name: fhir
    image: "irccs/fhir-server:1.0.2"
    environment:
      hapi.fhir.allow_external_references: "true"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db

  db:
    image: postgres:alpine3.18
    restart: always
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    ports:
      - "5432:5432"


  cache:
    image: redis:7.0-rc
    ports:
      - 6379:6379
    command: >
      --requirepass password

  httpd:
    image: irccs/httpd:2.4.46
    volumes:
      - ./html/:/usr/local/apache2/htdocs
    ports:
      - 80:80


configs:
  hapi:
    file: ./hapi.application.yaml