version: '3.1'

services:
  fhir-api:
    image: "mcr.microsoft.com/healthcareapis/r4-fhir-server"
    restart: on-failure
    environment:
      FHIRServer__Security__Enabled: "false"
      SqlServer__ConnectionString: "Server=tcp:sql,1433;Initial Catalog=dbo;Persist Security Info=False;User ID=sa;Password=yourStrong(!)Password;MultipleActiveResultSets=False;Connection Timeout=30;TrustServerCertificate=false;Encrypt=False;"
      SqlServer__AllowDatabaseCreation: "true"
      SqlServer__Initialize: "true"
      SqlServer__SchemaOptions__AutomaticUpdatesEnabled: "true"
      DataStore: "SqlServer"
    ports:
      - "8080:8080"

  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  java-env:
    image: "irccs/17-jdk"
    volumes:
    - ./services/:/home


  httpd:
    image: irccs/httpd:2.4.46
    volumes:
      - ./html/:/usr/local/apache2/htdocs
    ports:
      - 80:80