version: '3.8'

services:
  irccs-httpd:
    container_name: irccs-httpd
    image: nexus.infocube.it/org.quarkus/irccs-httpd:1.0.0-SNAPSHOT
    restart: always
    ports:
      - 80
    networks:
      - irccs-docker_default
    volumes:
     #- ./httpd-files/./htdocs /usr/local/apache2/htdocs/
      - ./httpd-config/irccs.conf:/usr/local/apache2/conf/sites/irccs.conf
      - ./httpd-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
networks:
  irccs-docker_default:
    external: true

