# Cartella locale dove salvare i DICOM anonimizzati
dicom.storage.path=/home/infocube/Desktop/tmp_tac/dicom-anon

quarkus.http.limits.max-body-size=5G

# (opzionale) dove RESTEasy Reactive mette i temp FileUpload
quarkus.http.uploads.directory=/home/infocube/Desktop/tac_upload

# (opzionale) estensione massima nome file
quarkus.http.uploads.max-file-size=5G