quarkus.http.port=8080
# Variables
quarkus.log.level=INFO
quarkus.rest-client.auth-microservice-client.url=http://irccs-auth:8080

# Keycloak Variables
keycloak-port=8080
keycloak-base-url=http://irccs-keycloak:${keycloak-port}

# Keycloak Configuration
keycloak-client_id=${KEYCLOAK_CLIENT_ID}
keycloak-client_secret=${KEYCLOAK_CLIENT_SECRET}
keycloak-realm=${KEYCLOAK_REALM}
keycloak-admin-username=${KEYCLOAK_ADMIN}
keycloak-admin-password=${KEYCLOAK_ADMIN_PASSWORD}

quarkus.http.cors.exposed-headers=Content-Disposition, Authorization
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with, content-disposition

# ZAMMAD CONFIG
zammad.base-url=${ZAMMAD_BASE_URL}
zammad.token=${ZAMMAD_TOKEN_SERVICE}

# KC Auth Server Url
quarkus.oidc.token.issuer=${OIDC_TOKEN_ISSUER}
quarkus.oidc.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL}

zammad.sync.interval=${ZAMMAD_INTERVAL_POLLING}
zammad.admin.email=${ZAMMAD_ADMIN_EMAIL}
quarkus.rest-client.zammad-api.url=${ZAMMAD_BASE_URL}

