quarkus.http.port=8080
# Variables
quarkus.log.level=INFO
quarkus.rest-client.auth-microservice-client.url=http://irccs-auth:8080

# Keycloak Variables
keycloak-port=8080
keycloak-base-url=http://irccs-keycloak

# Keycloak Configuration
keycloak-client_id=irccs
keycloak-client_secret=cwvB6qAn5iFl7pa9r04WxkordJyy3tjS
keycloak-realm=pascale
keycloak-admin-username=gennaro.aurilia@gmail.com
keycloak-admin-password=Qwerty123!

quarkus.http.cors.exposed-headers=Content-Disposition, Authorization
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with, content-disposition

# ZAMMAD CONFIG
zammad.base-url=https://zammad.infocube.it/api/v1/
zammad.token=VXCjDiX6lyztoSPKBURwtA07-Pf0o2LDrGC_7uD8XdGvU22XVgV-Vqw5E9hutC6g

# KC Auth Server Url
quarkus.oidc.token.issuer=https://backoffice.irccs.infocube.it/realms/pascale



