quarkus.http.port=8080
# Variables
quarkus.log.level=INFO
quarkus.rest-client.auth-microservice-client.url=http://irccs-auth:8080

# Keycloak Variables
keycloak-port=8080
keycloak-base-url=http://irccs-keycloak:8080/backoffice


# Keycloak Configuration
keycloak-client_id=${KEYCLOAK_CLIENT_ID}
keycloak-client_secret=${KEYCLOAK_CLIENT_SECRET}
keycloak-realm=${KEYCLOAK_REALM}
keycloak-admin-username=${KEYCLOAK_ADMIN}
keycloak-admin-password=${KEYCLOAK_ADMIN_PASSWORD}

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true
quarkus.keycloak.policy-enforcer.paths.0.path=/fhir/auth/users/signup
quarkus.keycloak.policy-enforcer.paths.1.path=/fhir/auth/users/token
quarkus.keycloak.policy-enforcer.paths.2.path=/fhir/auth/users/logout
quarkus.keycloak.policy-enforcer.paths.3.path=/fhir/auth/users/forgotPassword
quarkus.keycloak.policy-enforcer.paths.4.path=/fhir/auth/users/updatePassword
quarkus.keycloak.policy-enforcer.paths.5.path=/fhir/auth/users/me
quarkus.keycloak.policy-enforcer.paths.6.path=/fhir/auth/users/organizations
quarkus.keycloak.policy-enforcer.paths.0.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.2.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.3.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.4.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.5.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.6.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.http-method-as-scope=true

# KC Auth Server Url
quarkus.oidc.token.issuer=${OIDC_TOKEN_ISSUER}
quarkus.oidc.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL}
mp.jwt.verify.publickey.location=${QUARKUS_OIDC_AUTH_SERVER_URL}/protocol/openid-connect/certs

quarkus.oidc.token.verification=jwt
quarkus.oidc.application-type=service

quarkus.http.cors.exposed-headers=Content-Disposition, Authorization
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with, content-disposition

# ZAMMAD CONFIG
zammad.base-url=${ZAMMAD_BASE_URL}
zammad.token=${ZAMMAD_TOKEN_SERVICE}

# KC Auth Server Url
quarkus.oidc.token.issuer=${OIDC_TOKEN_ISSUER}
quarkus.oidc.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL}
mp.jwt.verify.publickey.location=${QUARKUS_OIDC_AUTH_SERVER_URL}/protocol/openid-connect/certs

zammad.sync.interval=${ZAMMAD_INTERVAL_POLLING}
zammad.admin.email=${ZAMMAD_ADMIN_EMAIL}
quarkus.rest-client.zammad-api.url=${ZAMMAD_BASE_URL}

