# Configuration used by K8S
%k8s.quarkus.http.port=9090
%k8s.hapi.base-url=http://10.99.88.210
%k8s.org.quarkus.irccs.fhir-server=http://10.99.88.210/fhir

# Keycloak Variables - K8S
%k8s.keycloak-port=9445
%k8s.keycloak-domain=http://10.99.88.210
%k8s.keycloak-url=http://10.99.88.210:9445

# Variables

%k8s.keycloak-client_id=irccs
%k8s.keycloak-client_secret=cwvB6qAn5iFl7pa9r04WxkordJyy3tjS
%k8s.keycloak-realm=pascale
%k8s.keycloak-admin-username=pascale@admin.it
%k8s.keycloak-admin-password=admin
%k8s.keycloak-grant-type=CLIENT_CREDENTIALS

quarkus.http.port=8181
quarkus.log.level=INFO

# Reference to microservice auth -> we really need this
%k8s.quarkus.rest-client.auth-microservice-client.url=http://irccs-auth:9090
%k8s.quarkus.rest-client.group-microservice-client.uri=http://irccs-centro-ricerca:8181

%prod.quarkus.rest-client.auth-microservice-client.url=http://irccs-auth:9090
%prod.quarkus.rest-client.group-microservice-client.url=http://irccs-centro-ricerca:8181

# FHIR R5 Server configuration - PROD
%prod.org.quarkus.irccs.fhir-server=http://fhir:8080/fhir
%prod.org.quarkus.irccs.query.limit=100

# Keycloak Variables - PROD
%prod.keycloak-port=9445
%prod.keycloak-domain=http://irccs-keycloak
%prod.keycloak-url=${keycloak-domain}

# Quarkus Dev Services configuration
quarkus.devservices.enabled=true
quarkus.devservices.timeout=10m

# Quarkus Dev Services hapi server version -> i3-client
#quarkus.hapi.devservices.version=7.2.0

# Quarkus Dev Services keycloak configuration -> i3-annotation
#quarkus.keycloak.devservices.image-name=keycloak/keycloak:24.0.5

#test port
quarkus.http.test-port=8083
quarkus.http.test-ssl-port=8446
quarkus.http.test-timeout=90s
