# Variables
quarkus.log.level=INFO
quarkus.rest-client.auth-microservice-client.url=http://irccs-auth:8080
quarkus.rest-client.group-microservice-client.url=http://irccs-centro-ricerca:8080
quarkus.rest-client.practitioner-microservice-client.url=http://irccs-practitioner:8080

# FHIR Server configuration
org.quarkus.irccs.fhir-server=http://irccs-hapi-fhir:8080/fhir
org.quarkus.irccs.query.limit=100

# Keycloak Variables
keycloak-port=8080
keycloak-base-url=http://irccs-keycloak


# Keycloak Configuration
keycloak-client_id=irccs
keycloak-client_secret=cwvB6qAn5iFl7pa9r04WxkordJyy3tjS
keycloak-realm=pascale
keycloak-admin-username=gennaro.aurilia@gmail.com
keycloak-admin-password=Qwerty123!

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true
quarkus.keycloak.policy-enforcer.paths.0.path=/fhir/auth/users/signup
quarkus.keycloak.policy-enforcer.paths.1.path=/fhir/auth/users/token
quarkus.keycloak.policy-enforcer.paths.2.path=/fhir/auth/users/logout
quarkus.keycloak.policy-enforcer.paths.3.path=/fhir/auth/users/forgotPassword
quarkus.keycloak.policy-enforcer.paths.4.path=/fhir/auth/users/updatePassword
quarkus.keycloak.policy-enforcer.paths.5.path=/fhir/auth/users/me
quarkus.keycloak.policy-enforcer.paths.6.path=/fhir/auth/users/organizations
quarkus.keycloak.policy-enforcer.paths.0.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.2.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.3.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.4.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.5.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.6.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.http-method-as-scope=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-hapi-fhir/hapi
quarkus.hibernate-orm.database.generation=none

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=../scripts/report

