# Variables
quarkus.log.level=INFO
%prod.quarkus.rest-client.auth-microservice-client.url=http://irccs-auth:9090
%prod.quarkus.rest-client.group-microservice-client.url=http://irccs-centro-ricerca:8181

# FHIR R5 Server configuration - PROD
%prod.org.quarkus.irccs.fhir-server=http://10.99.88.204:8080/fhir
%prod.org.quarkus.irccs.query.limit=100

# Keycloak Variables - PROD
%prod.keycloak-port=9445
%prod.keycloak-domain=http://10.99.88.204
%prod.keycloak-url=${keycloak-domain}:${keycloak-port}

# Quarkus Dev Services configuration
quarkus.devservices.enabled=true
quarkus.devservices.timeout=10m

# Quarkus Dev Services hapi server version -> i3-client
#quarkus.hapi.devservices.version=7.2.0

# Quarkus Dev Services keycloak configuration -> i3-annotation
#quarkus.keycloak.devservices.image-name=keycloak/keycloak:24.0.5

#test port
quarkus.http.test-port=8083
quarkus.http.test-ssl-port=8446
quarkus.http.test-timeout=90s
